CREATE TABLE `oder` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `order_sn` varchar(70)  '订单号',
  `goods_id` int(30) COMMENT '商品id',
  `goods_name` varchar(79) DEFAULT NULL COMMENT '商品名',
  `goods_thumbnail_url` varchar(120) DEFAULT NULL COMMENT '商品图片url',
  `goods_quantity` int(10) DEFAULT 0 COMMENT '购买商品的数量',
  `goods_price` int(20) DEFAULT 0 COMMENT '订单中sku的单件价格，单位为分',
  `order_amount` int(20)  DEFAULT 0 COMMENT '实际支付金额，单位为分',
	`p_id` int(20)  DEFAULT 0 COMMENT '推广位ID',
  `promotion_rate` bigint(20) DEFAULT 0 COMMENT '佣金比例，千分比',
	 `promotion_amount` bigint(20) DEFAULT 0 COMMENT '佣金金额，单位为分',
  `order_status` int(5) DEFAULT -1 COMMENT '订单状态： -1 未支付;0-已支付；1-已成团；2-确认收货；3-审核成功；4-审核失败（不可提现）；5-已经结算；8-非多多进宝商品（无佣金订单）',
	  `order_status_desc` varchar(50) DEFAULT NULL COMMENT '订单状态描述',
	`order_create_time` bigint(20)  DEFAULT 0 COMMENT '订单生成时间，UNIX时间戳',
	`order_pay_time` bigint(20) DEFAULT 0 COMMENT '支付时间',
		`order_group_success_time` bigint(20) DEFAULT 0 COMMENT '成团时间',
		`order_verify_time` bigint(20) DEFAULT 0 COMMENT '审核时间',
	 `order_modify_at` bigint(20) DEFAULT 0 COMMENT '最后更新时间',
  `createTime` datetime DEFAULT NULL COMMENT '创建时间',
  `updateTime` datetime DEFAULT NULL ,
  `status` tinyint(4) DEFAULT '0' COMMENT '0正常;1冻结',
  PRIMARY KEY (`id`),
  KEY `order_sn` (`order_sn`),
  KEY `p_id` (`p_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='订单表';
