//package com.neo.dao;
//
//import com.neo.model.TboderBean;
//
//import java.util.List;
//
//public interface TbOderDao {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tboder
//     *
//     * @mbggenerated
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tboder
//     *
//     * @mbggenerated
//     */
//    int insert(TboderBean record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tboder
//     *
//     * @mbggenerated
//     */
//    Integer selectPidIn(List list);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tboder
//     *
//     * @mbggenerated
//     */
//    TboderBean selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tboder
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKeySelective(TboderBean record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table tboder
//     *
//     * @mbggenerated
//     */
//    int updateByPrimaryKey(TboderBean record);
//}