package com.neo.dao;

import com.neo.model.SysJhAdviceOder;
import com.neo.model.Tboder;
import com.neo.model.Userinfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface TbOderDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int insert(Tboder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    Integer selectPidIn(List list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    Tboder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tboder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tboder record);

    @Select("select id from tboder where trade_id=#{trkId}")
    Integer findIs(Long trkId);

    /**
     * 检查订单是否已经存在
     *
     * @param
     * @return
     */
    Integer oderUpdate(@Param("tb") Tboder tb);

    /**
     * 检查订单是否已经存在
     *
     * @param
     * @return
     */
    Integer saveTbOderAdvice(SysJhAdviceOder sysJhAdviceOder);



    Userinfo queryUserForPid(Userinfo userinfo);

}