package com.neo.dao;

import com.neo.model.SysJhAdviceOder;
import com.neo.model.TboderBean;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface TbOderDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int insert(TboderBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    Integer selectPidIn(List list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
//    TboderBean selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TboderBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tboder
     *
     * @mbggenerated
     */
//    int updateByPrimaryKey(TboderBean record);

    @Select("select id from tboder where trade_id=#{trkId}")
    Integer findIs(Long trkId);

    /**
     * 检查订单是否已经存在
     *
     * @param
     * @return
     */
    Integer oderUpdate(@Param("tb") TboderBean tb);

    /**
     * 检查订单是否已经存在
     *
     * @param
     * @return
     */
    Integer saveTbOderAdvice(SysJhAdviceOder sysJhAdviceOder);


    /**
     * 扫描淘宝已结算订单
     *
     * @param
     * @return
     */
    @Select("select * from tboder where tk_status=1 and settle=0")
    List<TboderBean> scanTaoBaoOder();

    /**
     * 更新淘宝的订单
     *
     * @param
     * @return
     */
    Integer taoBaoUpdate(TboderBean tboderBean);



}