pdd_pro:
  pdd-key: bbc1737d63e44e278dbffa9e96a7eca3
  pdd-secret: 5e1a03eb561bac0c63c5efc8c1472119fc3ad405
  pdd-access_token: fd5d312adc6e4200bcf314cf943a287593ee3f07
  pdd-url: https://wj.hxksky.com
  pdd-router-url: https://gw-api.pinduoduo.com/api/router

domain:
  url: "http://120.79.62.89/"
  codeurl: "http://120.79.62.89:8080"
  localurl: "http://192.168.0.102"
  jdimageurl: "http://img14.360buyimg.com/n1/"
  jdUrl: "https://router.jd.com/api"
  jdsecret: "909a02d9f2e845578f6333a3a13ea5cd"
  jdkey: "1b2eadd4ad604021a9e48aa5726c503b"
  jduid: "1001142862"

server:
    port: 8089
spring:

  redis:
    database: 0
#    host: 121.201.43.229
#    host: 192.168.1.6
    host: 127.0.0.1
    port: 6379
#    password: huazhongBAO
    password:
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
    timeout: 20000

  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      #基本属性
#      url: jdbc:mysql://192.168.1.6:3306/yetdwell?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      url: jdbc:mysql://120.79.62.89:3306/yetdwell?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: gg5201314
#      password: huazhongno1
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

logging:
  level:
    com.superman.superman: DEBUG
  file: ./logs/core.log
  root: DEBUG


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.neo.model

juanhuang:
  range: 90

miao:
  apkey: "bb67403e-b370-681d-139c-770100c8eec2"
  tbname: "华众有个店"
  url: "https://api.open.21ds.cn/jd_api_v1/"

